### ISSUE TITLE
hi, 

### ISSUE THREAD

**Issue by bsdj2** [hamburgerlady/fast_planar_camera_pose#1]
I am very interested in this work. Do you have text description of this algorithm，such as paper or book？Thanks.

**Comment by hamburgerlady** [comment]
Hi, 
nice that you're interested! There's an Arxiv paper that describes the method,
"A fast minimal solver for absolute camera pose with unknown focal length and radial distortion from four planar points", see link below
https://arxiv.org/abs/1805.10705

If you have any other questions, please let me know

**Comment by bsdj2** [comment]
thanks very much

**Comment by bsdj2** [comment]
I have another problem. Is **R1sol** a row or a col of **Rsol** in code？Is it equal to the vector **(r11, r12, r13)** in paper？
I have try a few combinations, but can't get the correct projected coordinates. such as...
`     r = [R1sol (1, 1), R1sol (2, 1), tsol (1, 1);
            R2sol (1, 1), R2sol (2, 1), tsol (2, 1);
            R3sol (1, 1), R3sol (2, 1), tsol (3, 1); ];`
and 
`   r = [R1so l(1, 1), R2sol (1, 1) ,tsol (1, 1);
           R1sol (2, 1), R2sol (2, 1), tsol (2, 1);
           R1sol (3, 1), R2sol (3, 1), tsol (3, 1); ];` 
I get, the second is correct~ I forget the distorted variable ksol
